---
title: "Items: German"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      toc_depth: 3
---
  
Here you can find a quick overview of all items that were measured.

## Life Satisfaction

"Alles in allem betrachtet, wie zufrieden sind Sie derzeit mit Ihrem Leben?" 

(0 = äußerst unzufrieden, 10 = äußerst zufrieden)

## Positive Affect (scale)

"Wie often waren Sie in der letzten Woche"

 - a: ... ruhig und gelassen
 - e: ... glücklich
 - i: ... voller Energie

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

## Negative Affect (scale)

"Wie often waren Sie in der letzten Woche"

 - b: ... einsam
 - c: ... ärgerlich
 - d: ... so niedergeschlagen, dass Sie nichts aufheitern konnte
 - f: ... sehr nervös
 - g: ... ängstlich
 - h: ... bedrückt und traurig

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

## Social media use: Reading 

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Postings anderer lesen, in denen es um Inhalte zum Coronavirus geht"

(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

## Social media use: Liking & Sharing

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Bei Postings anderer zum Coronavirus auf den „Gefällt mir“ Button drücken, „teilen“ oder „retweeten“"

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

## Social media use: Active Postings

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Selbst Postings zum Coronavirus in Sozialen Netzwerken verfasst"

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

## Social media use: Specific platforms

"Wie oft in der letzten Woche haben Sie Informationen zur Corona-Krise in den folgenden Sozialen Medien verfolgt?"

 - Facebook 
 - Twitter
 - Instagram
 - Youtube
 - WhatsApp
		
(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

## Gender

"Welches Geschlecht haben Sie?"

(a: Männlich; b Weiblich; c: Divers)

## Age

"In welchem Jahr wurden Sie geboren?"
 
(Jahr)

## Education

"Was ist der höchste Schul- oder Bildungsabschluss, den Sie erreicht haben?"

 - a. Volksschule oder weniger
 - b. Hauptschule oder AHS Unterstufe
 - c. Polytechnikum, BMS (Fachschule, z.B. HASCH)
 - d. Lehre, Berufsschule
 - e. AHS mit Matura
 - f. BHS mit Matura (z.B. HTL, HAK, HBLA etc.) 
 - g. Hochschulverwandte Lehranstalt oder Kolleg 
 - h. Bachelor
 - i. Magister / Master / Diplomingenieur / Fachhochschule 
 - j. Doktor / PhD

## Austria country of birth

"Ist Ihr Geburtsland Österreich?"

  - Ja
  - Nein

## Austria country of birth of parents

 "Wurde einer oder beide Ihrer Elternteile nicht in Österreich geboren?"
 
 - a. Ja, einer
 - b. Ja, beide
 - c. Nein

## News consumption: Text-based

"Nachstehend finden Sie eine Liste mit verschiedenen Tageszeitungen. Wie oft haben Sie sich letzte Woche über das politische Geschehen in der jeweiligen Zeitung (im Internet oder gedruckt) informiert?"

 - Kronen Zeitung oder www.krone.at
 - Der Standard oder derstandard.at
 - Die Presse oder diepresse.com
 - Österreich oder oe24.at
 - Kurier oder kurier.at
 - Salzburger Nachrichten oder salzburg.at
 - Sonstige österreichische Tageszeitungen

## News consumption: Video-based

"Nachstehend finden Sie eine Liste mit verschiedenen Nachrichtensendungen im Fernsehen. Wie oft haben Sie sich letzte Woche über das politische Geschehen in den folgenden Nachrichtensendungen informiert?"

 - "Nachrichtensendungen im ORF (z.B. Zeit im Bild um 19:30h oder ZiB 2 um 22:00h)"
 - "Nachrichtensendungen im Privatfernsehen (z.B. ATV aktuell, Puls 4/ Pro7/ Sat1 Austria)"

(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

## Residency Vienna

"In welchem Bundesland leben Sie aktuell?"

 - a. Vorarlberg
 - b. Tirol
 - c. Salzburg
 - d. Steiermark
 - e. Kärnten
 - f. Oberösterreich
 - g. Niederösterreich
 - h. Wien
 - i. Burgenland

(Will be transformed to Vienna: yes/no)

## Household size

"Bitte rechnen Sie hier sich selbst wieder mit ein. Wenn es eine Personengruppe nicht in Ihrem Haushalt gibt, tragen Sie bitte „0“ ein.

 - a. ...Erwachsene über 18 Jahre:
 - b. ...Teenager von 15-17 Jahren:
 - c. ...Kinder von 6-14 Jahren:
 - d. ...Kinder von 3-5 Jahren:
 - e. ...Kinder von 0-2 Jahren:

(Achtung, wenn Anzahl Erwachsene missing, 1 eintragen, da vorher Filterfrage)

## Health

"Kommen wir jetzt zu ein paar Fragen zu Ihrer Gesundheit. Wie schätzen Sie Ihren allgemeinen Gesundheitszustand ein? Würden Sie sagen, er ist..."

 - a. 1 = Sehr gut
 - b. 2 = Gut
 - c. 3 = Mittelmäßig
 - d. 4 = Schlecht
 - e. 5 = Sehr schlecht

## Living space

"Wie viele Quadratmeter hat Ihre Wohnung?"

(Einfach-Nennung, Zahleneingabe, min. 0 – max. 600, freiwillig)

## Access garden

"Haben Sie Zugang zu einer privaten Freifläche (Balkon, Garten)? 

 - (Ja, Garten)

## Access balcony

"Haben Sie Zugang zu einer privaten Freifläche (Balkon, Garten)?" 

 - (Ja, Balkon)

## Employment

Wenn Sie sich selbst zuordnen: Im Februar 2020, welcher der folgenden Gruppen gehören Sie vorwiegend an? (Einfach-Nennung)

 - a. Unselbstständig erwerbstätig (auch Lehrling), Privatwirtschaft
 - b. Unselbstständig erwerbstätig (auch Lehrling), Öffentlicher Dienst
 - c. Selbstständig erwerbstätig
 - d. Arbeitslos
 - e. Pensionist*in
 - f. Ausschließlich haushaltsführend
 - g. Schüler/in, Student/in, Bildungskarenz
 - h. Dauerhaft arbeitsunfähig
 - i. Präsenz-/Zivildiener
 - j. In Elternkarenz
		
## Work hours per week

"Wie viele Stunden (inklusive Überstunden) arbeiten Sie in Ihrer Haupttätigkeit jetzt pro Woche? Wenn Sie es nicht genau wissen, genügt Ihre beste Schätzung."

## Home-Office Yes/No

"Hat sich in Ihrer beruflichen Situation aufgrund der Corona-Krise etwas geändert? Bitte wählen Sie alles Zutreffende aus."

 - a. Ich bin im Home-Office

## Household income

"Wie viel Geld steht Ihrem Haushalt aktuell zur Verfügung (Netto-Haushaltseinkommen inklusive Sozialleistungen, Rente usw.)? Bitte rechnen Sie Überstunden mit ein, nicht aber den 13./14. Bezug."

 - a. weniger als 1.100 Euro
 - b. 1.100 bis unter 1.500 Euro 
 - c. 1.500 bis unter 1.800 Euro 
 - d. 1.800 bis unter 2.200 Euro 
 - e. 2.200 bis unter 2.700 Euro 
 - f. 2.700 bis unter 3.100 Euro 
 - g. 3.100 bis unter 3.700 Euro 
 - h. 3.700 bis unter 4.300 Euro 
 - i. 4.300 bis unter 5.500 Euro 
 - j. 5.500 Euro und mehr

## Outdoor activities

"Haben Sie wegen folgenden Gründen in der vergangenen Woche Ihr Zuhause verlassen?"

 - a: Arbeit
 - b: Sport
 - c: Freunde oder Verwandte treffen
 - e: Essen einkaufen
 - f: Haustiere ausführen
	
(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

## Satisfaction Democracy

"Wie zufrieden oder unzufrieden sind Sie alles in allem mit der Demokratie, so wie sie derzeit in Österreich funktioniert?"

 - a. 1 = Sehr zufrieden
 - b. 2 = Eher zufrieden
 - c. 3 = Teils-teils
 - d. 4 = Eher unzufrieden 
 - e. 5 = Sehr unzufrieden

## Risk-taking

"Wie sehr sind Sie im Allgemeinen dazu bereit, Risiken einzugehen?"

(0: gar nicht bereit; 10: sehr bereit)

## Locus of Control 

 - "Ich habe mein Leben selbst in der Hand."
 - "Wenn ich mich anstrenge, werde ich auch Erfolg haben."
 - "Egal ob privat oder im Beruf: Mein Leben wird zum großen Teil von anderen bestimmt."
 - "Meine Pläne werden oft vom Schicksal durchkreuzt."
	
(1 = Trifft voll und ganz zu; 2 = Trifft etwas zu; 3 = Trifft wenig zu; 4 = Trifft nicht zu)