---
title: "Preregistration"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      toc_depth: 3
---

The actual preregistration can be found [here](https://osf.io/87b24/?view_only=b2289b6fec214fa88ee75a18d45c18f3). I have also pasted it below.

## Hypotheses

The within-person effects of all types of COVID-19 related social media use on all types of well-being indicators will be trivial, while controlling for several stable and varying covariates such as  sociodemographic variables and psychological dispositions.

## Design Plan
#### Study type

Observational Study - Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, “natural experiments,” and regression discontinuity designs.

#### Blinding

No blinding is involved in this study.

#### Is there any additional blinding in this study?

No response

## Study design

Secondary data analysis of a questionnaire-based panel study with 24 waves that consist of at least 1,500 participants per wave. A large number of questions was collected each, and a subset will be used for this study.

#### Randomization

No response

#### Sampling Plan

Existing Data

Registration prior to accessing the data

#### Explanation of existing data

I will analyze the Austrian Corona Panel. The data are posted on AUSSDA (https://doi.org/10.11587/28KQNS). I have not yet accessed the data. I have used the study description online to design the preregistration. After finishing the preregistration, I plan to create a login on AUSSDA. I will then download the scientific use file. In case the use file should not contain some of the variables I preselected, or if they are recoded such that the variables cannot be used, I will directly contact the study authors to ask for access to the original data set. In case this won't be possible, I will slightly change the analyses so that I can use the scientific use file.

#### Data collection procedures

I will use the already existing data set. Information on how the data was collected can be found here: https://viecer.univie.ac.at/coronapanel/austrian-corona-panel-data/method-report/

#### Sample size

The sample consists of at least 1,500 respondents per wave. Panel attrition was remedied by collecting new respondents. The overall and final sample size is not reported online, and will know it once I have downloaded the final data set.

#### Sample size rationale

The sample size was predetermined by the original study authors.

#### Stopping rule

Data collection is already finished.

## Variables
#### Manipulated variables

No variables were manipulated.

#### Measured variables

(Note: To improve readability, compared to the actual [preregistration](https://osf.io/87b24/?view_only=b2289b6fec214fa88ee75a18d45c18f3) the following part was reformatted and partially translated. No actual changes were introduced.)

In what follows, I list all the variables that I will use for the analyses (which also means that they cannot be dropped later). Note that the data set contains many more variables that I will not use. I provide the variable name in English, and the response options, answer format, and items in German.

###### Life Satisfaction

"Taken everything together, how satisfied are you currently with your life?" 

(0 = extremely unsatisfied, 10 = extremely satisfied)

###### Positive Affect (scale)

"In the last week, how often did you feel"

 - a: ... calm and relaxed
 - e: ... happy
 - i: ... full of energy

(never [1]; on some days [2]; several times per week [3]; almost every day [4]; daily [5])

###### Negative Affect (scale)

"In the last week, how often did you feel"

 - b: ... lonely
 - c: ... aggravated
 - d: ... so depressed, that nothing could lift you up
 - f: ... very nervous
 - g: ... anxious
 - h: ... glum and sad

(never [1]; on some days [2]; several times per week [3]; almost every day [4]; daily [5])

###### Social media use: Reading 

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Postings anderer lesen, in denen es um Inhalte zum Coronavirus geht"

(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

###### Social media use: Liking & Sharing

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Bei Postings anderer zum Coronavirus auf den „Gefällt mir“ Button drücken, „teilen“ oder „retweeten“"

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

###### Social media use: Active Postings

"Wie oft haben Sie letzte Woche die folgenden Aktivitäten in Sozialen Netzwerken gesetzt?" 

 - "Selbst Postings zum Coronavirus in Sozialen Netzwerken verfasst"

(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

###### Social media use: Specific platforms

"Wie oft in der letzten Woche haben Sie Informationen zur Corona-Krise in den folgenden Sozialen Medien verfolgt?"

 - Facebook 
 - Twitter
 - Instagram
 - Youtube
 - WhatsApp
		
(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

###### Gender

"Welches Geschlecht haben Sie?"

(a: Männlich; b Weiblich; c: Divers)

###### Age

"In welchem Jahr wurden Sie geboren?"
 
(Jahr)

###### Education

"Was ist der höchste Schul- oder Bildungsabschluss, den Sie erreicht haben?"

 - a. Volksschule oder weniger
 - b. Hauptschule oder AHS Unterstufe
 - c. Polytechnikum, BMS (Fachschule, z.B. HASCH)
 - d. Lehre, Berufsschule
 - e. AHS mit Matura
 - f. BHS mit Matura (z.B. HTL, HAK, HBLA etc.) 
 - g. Hochschulverwandte Lehranstalt oder Kolleg 
 - h. Bachelor
 - i. Magister / Master / Diplomingenieur / Fachhochschule 
 - j. Doktor / PhD

###### Austria country of birth

"Ist Ihr Geburtsland Österreich?"

  - Ja
  - Nein

###### Austria country of birth of parents

 "Wurde einer oder beide Ihrer Elternteile nicht in Österreich geboren?"
 
 - a. Ja, einer
 - b. Ja, beide
 - c. Nein

###### News consumption: Text-based

"Nachstehend finden Sie eine Liste mit verschiedenen Tageszeitungen. Wie oft haben Sie sich letzte Woche über das politische Geschehen in der jeweiligen Zeitung (im Internet oder gedruckt) informiert?"

 - Kronen Zeitung oder www.krone.at
 - Der Standard oder derstandard.at
 - Die Presse oder diepresse.com
 - Österreich oder oe24.at
 - Kurier oder kurier.at
 - Salzburger Nachrichten oder salzburg.at
 - Sonstige österreichische Tageszeitungen

###### News consumption: Video-based

"Nachstehend finden Sie eine Liste mit verschiedenen Nachrichtensendungen im Fernsehen. Wie oft haben Sie sich letzte Woche über das politische Geschehen in den folgenden Nachrichtensendungen informiert?"

 - "Nachrichtensendungen im ORF (z.B. Zeit im Bild um 19:30h oder ZiB 2 um 22:00h)"
 - "Nachrichtensendungen im Privatfernsehen (z.B. ATV aktuell, Puls 4/ Pro7/ Sat1 Austria)"

(1 = Mehrmals täglich; 2 = Einmal täglich; 3 = Mehrmals in der Woche; 4 = Einmal in der Woche; 5 = Gar nicht/nie)

###### Residency Vienna

"In welchem Bundesland leben Sie aktuell?"

 - a. Vorarlberg
 - b. Tirol
 - c. Salzburg
 - d. Steiermark
 - e. Kärnten
 - f. Oberösterreich
 - g. Niederösterreich
 - h. Wien
 - i. Burgenland

(Will be transformed to Vienna: yes/no)

###### Household size

"Bitte rechnen Sie hier sich selbst wieder mit ein. Wenn es eine Personengruppe nicht in Ihrem Haushalt gibt, tragen Sie bitte „0“ ein.

 - a. ...Erwachsene über 18 Jahre:
 - b. ...Teenager von 15-17 Jahren:
 - c. ...Kinder von 6-14 Jahren:
 - d. ...Kinder von 3-5 Jahren:
 - e. ...Kinder von 0-2 Jahren:

(Achtung, wenn Anzahl Erwachsene missing, 1 eintragen, da vorher Filterfrage)

###### Health

"Kommen wir jetzt zu ein paar Fragen zu Ihrer Gesundheit. Wie schätzen Sie Ihren allgemeinen Gesundheitszustand ein? Würden Sie sagen, er ist..."

 - a. 1 = Sehr gut
 - b. 2 = Gut
 - c. 3 = Mittelmäßig
 - d. 4 = Schlecht
 - e. 5 = Sehr schlecht

###### Living space

"Wie viele Quadratmeter hat Ihre Wohnung?"

(Einfach-Nennung, Zahleneingabe, min. 0 – max. 600, freiwillig)

###### Access garden

"Haben Sie Zugang zu einer privaten Freifläche (Balkon, Garten)? 

 - (Ja, Garten)

###### Access balcony

"Haben Sie Zugang zu einer privaten Freifläche (Balkon, Garten)?" 

 - (Ja, Balkon)

###### Employment

Wenn Sie sich selbst zuordnen: Im Februar 2020, welcher der folgenden Gruppen gehören Sie vorwiegend an? (Einfach-Nennung)

 - a. Unselbstständig erwerbstätig (auch Lehrling), Privatwirtschaft
 - b. Unselbstständig erwerbstätig (auch Lehrling), Öffentlicher Dienst
 - c. Selbstständig erwerbstätig
 - d. Arbeitslos
 - e. Pensionist*in
 - f. Ausschließlich haushaltsführend
 - g. Schüler/in, Student/in, Bildungskarenz
 - h. Dauerhaft arbeitsunfähig
 - i. Präsenz-/Zivildiener
 - j. In Elternkarenz
		
###### Work hours per week

"Wie viele Stunden (inklusive Überstunden) arbeiten Sie in Ihrer Haupttätigkeit jetzt pro Woche? Wenn Sie es nicht genau wissen, genügt Ihre beste Schätzung."

###### Home-Office Yes/No

"Hat sich in Ihrer beruflichen Situation aufgrund der Corona-Krise etwas geändert? Bitte wählen Sie alles Zutreffende aus."

 - a. Ich bin im Home-Office

###### Household income

"Wie viel Geld steht Ihrem Haushalt aktuell zur Verfügung (Netto-Haushaltseinkommen inklusive Sozialleistungen, Rente usw.)? Bitte rechnen Sie Überstunden mit ein, nicht aber den 13./14. Bezug."

 - a. weniger als 1.100 Euro
 - b. 1.100 bis unter 1.500 Euro 
 - c. 1.500 bis unter 1.800 Euro 
 - d. 1.800 bis unter 2.200 Euro 
 - e. 2.200 bis unter 2.700 Euro 
 - f. 2.700 bis unter 3.100 Euro 
 - g. 3.100 bis unter 3.700 Euro 
 - h. 3.700 bis unter 4.300 Euro 
 - i. 4.300 bis unter 5.500 Euro 
 - j. 5.500 Euro und mehr

###### Outdoor activities

"Haben Sie wegen folgenden Gründen in der vergangenen Woche Ihr Zuhause verlassen?"

 - a: Arbeit
 - b: Sport
 - c: Freunde oder Verwandte treffen
 - e: Essen einkaufen
 - f: Haustiere ausführen
	
(nie [1]; an manchen Tagen [2]; mehrmals die Woche [3]; beinahe jeden Tag [4]; täglich [5])

###### Satisfaction Democracy

"Wie zufrieden oder unzufrieden sind Sie alles in allem mit der Demokratie, so wie sie derzeit in Österreich funktioniert?"

 - a. 1 = Sehr zufrieden
 - b. 2 = Eher zufrieden
 - c. 3 = Teils-teils
 - d. 4 = Eher unzufrieden 
 - e. 5 = Sehr unzufrieden

###### Risk-taking

"Wie sehr sind Sie im Allgemeinen dazu bereit, Risiken einzugehen?"

(0: gar nicht bereit; 10: sehr bereit)

###### Locus of Control 

 - "Ich habe mein Leben selbst in der Hand."
 - "Wenn ich mich anstrenge, werde ich auch Erfolg haben."
 - "Egal ob privat oder im Beruf: Mein Leben wird zum großen Teil von anderen bestimmt."
 - "Meine Pläne werden oft vom Schicksal durchkreuzt."
	
(1 = Trifft voll und ganz zu; 2 = Trifft etwas zu; 3 = Trifft wenig zu; 4 = Trifft nicht zu)
#### Indices

All the measures above that include the label (scale) will be combined into a scale. These variables will be analyzed using CFAs. If, and only if, model fit is below the recommended thresholds, the models will be adapted to achieve sufficient fit (see below). To avoid overfitting, I will use more liberal model fit criteria (CFI > .90, TLI > .90, RMSEA <. .10, SRMR < .10). Of these final models I will export factor scores, which will be used for the subsequent analyses.

## Analysis Plan
#### Statistical models

The data will be analyzed using random effects within between models. The independent variables (all types of social media use) will be analyzed on a between person level (person average) and a within-person level (deviation from person average for each wave). 

Because the models are highly complex it is likely that they will not converge immediately. I plan the following analysis pipeline.

Analysis (proceed if doesn't converge):
- REWB Frequentist Model: Random Slope for Social Media Use & Covars
	- REWB Frequentist Model: Random Slope for Social Media Use & Fixed Slope for Covars
		- REWB Frequentist Model: Fixed Slope for Social Media Use  & Fixed Slope for Covars
			- REWB Frequentist Model: Fixed Slope for Social Media Use & Fixed Slope for Covars with standardized effects
				- REWB Bayesian Model
					- REWB Bayesian Model with standardized effects

CFA:
The factorial validity of the measures and the hypotheses will be tested with structural equation modeling (SEM). If Mardia’s test shows that the assumption of multivariate normality is violated, I will use the more robust Satorra-Bentler scaled and mean-adjusted test statistic (MLM) as estimator. I will test each scale in a confirmatory factor analysis. To avoid overfitting, I will use more liberal fit criteria (CFI > .90, TLI > .90, RMSEA <. .10, SRMR < .10) (Kline 2016). If model fit is below the criteria, I will first inspect modification indices, potentially allowing covariance or cross-loadings if theoretically plausible. If these changes do not yield sufficient fit, I will drop malfunctioning items. If fit is still subpar, I will conduct exploratory factor analyses (EFA) to assess the underlying factor structure. EFAs will be run using maximum likelihood estimation and oblimin rotation (Osborne and Costello 2004, 7). If more than one dimension will be revealed, I will implement bifactor model solutions. Bifactor models retain a general measure of the variable, and make it unnecessary to introduce novel (and potentially overfitted) subdimensions. If no adequate bifactor model can be found, I will proceed by deleting items with low loadings on the general factor and/or the specific factors. If also after deletion of individual items no bifactor solution should emerge, I will use a subset of the items to extract a single factor with sufficient factorial validity.

#### Transformations

See list of variables.

#### Inference criteria

Definition of trivial effect size (SESOI)

- b < .3 (life-satisfaction), b < .15 (positive and negative affect)
	- If I need to use standardized effects (see above): beta < .1
- in addition, p < 5%

#### Data exclusion

I will individually check responses for patterns such as straight-lining or missing of inverted items, making sure to remove only clear cases. I will exclude respondents if they answer less than 50% of all questions.

#### Missing data

Missing responses will be imputed using predictive mean matching.

#### Exploratory analysis

I will provide additional analyses online, such as the results without control variables. These aren't alternative results, but rather stem from procedures that I consider -- at this point -- to be inferior. 

## Other

It's a deliberate decision not to statistically control the analyses for potential mediators, such as trust in politics, media, etc.