---
title: "Preregistration: Changes"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      toc_depth: 3
---
  
The following changes were introduced after the preregistration.

## Covariates

I originally planned to include the following variables as varying covariates. I thought they were measured at several/all waves. However, upon seeing the actual data I realized this wasn't the case. I hence included them as stable covariates.

This includes residency is Vienna, self-reported physical health, living space (in squaremeter), access to balcony, access to garden, and employment status.

## Imputation

After having received feedback from colleagues who are experts on missing data analyses, I changed the imputation strategy.

- Before: predictive mean matching with n = 1 data-sets; now: multiple imputation (also predictive mean matching) with n = 5 data-sets.
- Before: remove participants with > 50% missing data; now: include all participants

## Estimation

Positive affect and negative affect were modeled as mean scores and not as factor scores. The reason was that it wasn't possible to extract factor scores for the data set with multiple imputation.